{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: fedlearner-proxy
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "fedlearner-add-on.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: {{ .Values.ingress.port }}
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: fedlearner-proxy
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.service.externalName }}
    ports:
      - port: {{ .Values.ingress.port }}
        name: grpc
        protocol: TCP
{{- end }}
